### ISSUE TITLE
Error when execute !bash scripts/train.sh dialdoc

### ISSUE THREAD

**Issue by wawatsmart** [ellenmellon/DIALKI#3]
When I execute !bash scripts/train.sh dialdoc,  error is show something like this :

================================================================================
                                    Epoch 0
================================================================================
Traceback (most recent call last):
  File "train_reader.py", line 919, in <module>
    main()
  File "train_reader.py", line 908, in main
    trainer.run_train()
  File "train_reader.py", line 278, in run_train
    self._train_epoch(epoch, train_dataloader)
  File "train_reader.py", line 494, in _train_epoch
    if train_dataloader.sampler.current_offset != 0:
AttributeError: 'RandomSampler' object has no attribute 'current_offset'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 18771) of binary: /opt/conda/bin/python
/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py:357: UserWarning: 

**********************************************************************
               CHILD PROCESS FAILED WITH NO ERROR_FILE                
**********************************************************************
CHILD PROCESS FAILED WITH NO ERROR_FILE
Child process 18771 (local_rank 0) FAILED (exitcode 1)
Error msg: Process failed with exitcode 1
Without writing an error file to <N/A>.
While this DOES NOT affect the correctness of your application,
no trace information about the error will be available for inspection.
Consider decorating your top level entrypoint function with
torch.distributed.elastic.multiprocessing.errors.record. Example:

  from torch.distributed.elastic.multiprocessing.errors import record

  @record
  def trainer_main(args):
     # do train
**********************************************************************
  warnings.warn(_no_error_file_warning_msg(rank, failure))
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 701, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 351, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 697, in main
    run(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 688, in run
    elastic_launch(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
***************************************
         train_reader.py FAILED        
=======================================
Root Cause:
[0]:
  time: 2022-05-21_13:24:06
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 18771)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
[1]:
  time: 2022-05-21_13:24:06
  rank: 1 (local_rank: 1)
  exitcode: 1 (pid: 18772)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
***************************************

​There are two error overthere, one is about random sampler and the other is about child process. Do you know what is the solution?

**Comment by L1ttleBad** [comment]
Met the same problem without initialize torch.distributed. Run code under distributed mode will avoid this problem.
