### ISSUE TITLE
Meeting "RuntimeError: CUDA out of memory" error in RTX 3090 with batch_size=1

### ISSUE THREAD

**Issue by L1ttleBad** [ellenmellon/DIALKI#6]
你好，我尝试使用RTX 3090 24G在Doc2Dial数据集上运行BERT Large模型，由于并行部分程序会卡住不动，我使用单卡运行。
运行参数如下
```
CUDA_VISIBLE_DEVICES=${cards} python train_reader.py \
    --pretrained_model_cfg ${parent_dir}/pretrained_models/bert-large-uncased \
    --seed 42 \
    --learning_rate 3e-5 \
    --eval_step 1000 \
    --do_lower_case \
    --eval_top_docs 20 \
    --warmup_steps 1000 \
    --max_seq_len ${max_seq_len} \
    --batch_size 1 \
    --passages_per_question ${passages_per_question} \
    --num_train_epochs 7 \
    --dev_batch_size 4 \
    --max_answer_length ${max_answer_length} \
    --passages_per_question_predict 20 \
    --train_file ${parent_dir}/cache/cls_bert/train \
    --dev_file ${parent_dir}/cache/cls_bert/dev \
    --output_dir $output_dir \
    --gradient_accumulation_steps 2 \
    --ignore_token_type \
    --decision_function 1 \
    --hist_loss_weight ${hist_loss_weight} \
    --fp16 \
    --fp16_opt_level O2 \
    --data_name ${data_name} \
    --adv_loss_type js \
    --adv_loss_weight 5 \
    --use_z_attn
```

在程序开始运行后，遇到了如下错误：
  
    ================================================================================
                                        Training
    ================================================================================
    Total updates = 68614.0
    Updates per epoch (/gradient accumulation) = 9802
    Steps per epoch (dataloader) = 19604
    Gradient accumulation steps = 2
    Start offset of the epoch 0 (dataset) = step 0
    Updated step of the epoch 0 (dataloader) = step 0
    Total remaining updates = 68614.0
    ================================================================================
                                        Epoch 0
    ================================================================================
    /home/xcruan/miniconda3/envs/dialki/lib/python3.8/site-packages/torch/optim/lr_scheduler.py:122: UserWarning: Seems like `optimizer.step()` has been overridden after learning rate scheduler initialization. Please, make sure to call `optimizer.step()` before `lr_scheduler.step()`. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
      warnings.warn("Seems like `optimizer.step()` has been overridden after learning rate scheduler "
    Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 16384.0
    Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 4096.0
    Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 2048.0
    Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 1024.0
    Traceback (most recent call last):
      File "train_reader.py", line 926, in <module>
        main()
      File "train_reader.py", line 914, in main
        trainer.run_train()
      File "train_reader.py", line 279, in run_train
        self._train_epoch(epoch, train_dataloader)
      File "train_reader.py", line 517, in _train_epoch
        losses, others = self._training_step(batch)
      File "train_reader.py", line 803, in _training_step
        logits, others = self.reader(batch, self.global_step)
      File "/home/xcruan/miniconda3/envs/dialki/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
        return forward_call(*input, **kwargs)
      File "/home/xcruan/miniconda3/envs/dialki/lib/python3.8/site-packages/apex/amp/_initialize.py", line 196, in new_fwd
        output = old_fwd(*applier(args, input_caster),
      File "/home/disk2/xcruan/doc2dial/dialki/models/reader.py", line 254, in forward
        adv_logits, emb_val, eff_perturb = self.adv_forward(
      File "/home/disk2/xcruan/doc2dial/dialki/models/reader.py", line 267, in adv_forward
        adv_logits, emb_val, eff_perturb = self.adv_teacher.forward(
      File "/home/disk2/xcruan/doc2dial/dialki/models/perturbation.py", line 64, in forward
        adv_logits, _ = model(batch, global_step, fwd_type='inputs_embeds', inputs_embeds=embed+noise, end_task_only=True)
      File "/home/xcruan/miniconda3/envs/dialki/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
        return forward_call(*input, **kwargs)
      File "/home/xcruan/miniconda3/envs/dialki/lib/python3.8/site-packages/apex/amp/_initialize.py", line 196, in new_fwd
        output = old_fwd(*applier(args, input_caster),
      File "/home/disk2/xcruan/doc2dial/dialki/models/reader.py", line 183, in forward
        sequence_output, _pooled_output, _hidden_states = self.encoder(
      File "/home/xcruan/miniconda3/envs/dialki/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
        return forward_call(*input, **kwargs)
      File "/home/disk2/xcruan/doc2dial/dialki/models/hf_models.py", line 108, in forward
        sequence_output, pooled_output = super().forward(
      File "/home/xcruan/miniconda3/envs/dialki/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 971, in forward
        encoder_outputs = self.encoder(
      File "/home/xcruan/miniconda3/envs/dialki/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
        return forward_call(*input, **kwargs)
      File "/home/xcruan/miniconda3/envs/dialki/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 568, in forward
        layer_outputs = layer_module(
      File "/home/xcruan/miniconda3/envs/dialki/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
        return forward_call(*input, **kwargs)
      File "/home/xcruan/miniconda3/envs/dialki/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 456, in forward
        self_attention_outputs = self.attention(
      File "/home/xcruan/miniconda3/envs/dialki/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
        return forward_call(*input, **kwargs)
      File "/home/xcruan/miniconda3/envs/dialki/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 387, in forward
        self_outputs = self.self(
      File "/home/xcruan/miniconda3/envs/dialki/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
        return forward_call(*input, **kwargs)
      File "/home/xcruan/miniconda3/envs/dialki/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 276, in forward
        value_layer = self.transpose_for_scores(self.value(hidden_states))
      File "/home/xcruan/miniconda3/envs/dialki/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
        return forward_call(*input, **kwargs)
      File "/home/xcruan/miniconda3/envs/dialki/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 103, in forward
        return F.linear(input, self.weight, self.bias)
      File "/home/xcruan/miniconda3/envs/dialki/lib/python3.8/site-packages/torch/nn/functional.py", line 1848, in linear
        return torch._C._nn.linear(input, weight, bias)
    RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 23.70 GiB total capacity; 21.47 GiB already allocated; 14.56 MiB free; 21.70 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

注意到显存已经用完，我尝试运行了BERT-base的版本，在batch size设置为2时占用19G的显存，在1080Ti 11G上则batch size为1都无法运行
注意到在Readme中提到能够在Q6000上运行代码，想请问下目前的显存占用是否有问题？或者能否提供bert-large的checkpoint以供测试。

**Comment by ellenmellon** [comment]
Hi, thanks for your interest. The parameters in the provided training script are for BERT-base only. If you'd like to try BERT-large, we suggest you to set a smaller number for `--passages_per_question` (say 4 or 5). We didn't run into any memory issue with the provided parameters for BERT-base and for your reference, our GPU has 24G memory.

In terms of the other issue you had when running with multiple GPUs, we had something similar (the program got stuck) at some point when the cuda version got upgraded. But we no longer have the issue, at least with the recent cuda version (11.6). Also, I notice that your command is not completely the same as what we put in the training script. Not sure whether that could be the cause of the issue as well.

**Comment by ellenmellon** [comment]
Also, I forgot to mention that, you can also try setting `--decision_function=0` in the training script, which can save some memory and you can probably set `--passages_per_question=6` in that case (with 24G memory). `--decision_function=0` disables the knowledge contextualization component, which I don't remember contributes much to the performance for BERT-large.

**Comment by L1ttleBad** [comment]
Due to not sure about code modification, I cloned the code again and ran with original scripts,
Noticing the program stucked within `option.setup_args_gpu(args)`.

By annotating init_method like below, code started to run.
```
        master_port = next_free_port()
        dist_init_method = f'tcp://localhost:{master_port}'
        torch.distributed.init_process_group(
            backend='nccl',
            #init_method=dist_init_method,
            rank=args.local_rank,
            world_size=word_size)
``` 

With lower parameters, we still met the 'CUDA out of memory‘ error.
```
python -m torch.distributed.launch --nproc_per_node $WORLD_SIZE train_reader.py \
    --pretrained_model_cfg ${parent_dir}/pretrained_models/bert-large-uncased \
    --seed 42 \
    --learning_rate 3e-5 \
    --eval_step 1000 \
    --do_lower_case \
    --eval_top_docs 20 \
    --warmup_steps 1000 \
    --max_seq_len ${max_seq_len} \
    --batch_size 1 \
    --passages_per_question ${passages_per_question} \
    --num_train_epochs 5 \
    --dev_batch_size 4 \
    --max_answer_length ${max_answer_length} \
    --passages_per_question_predict 4 \
    --train_file ${parent_dir}/cache/cls_bert/train \
    --dev_file ${parent_dir}/cache/cls_bert/dev \
    --output_dir $output_dir \
    --gradient_accumulation_steps 2 \
    --ignore_token_type \
    --decision_function 0 \
    --hist_loss_weight ${hist_loss_weight} \
    --fp16 \
    --fp16_opt_level O2 \
    --data_name ${data_name} \
    --adv_loss_type js \
    --adv_loss_weight 5 \
    --use_z_attn
```

**Comment by ellenmellon** [comment]
Did you try setting `--passages_per_question` to 4 as well, or just `--passages_per_question_predict`?

**Comment by L1ttleBad** [comment]
hhhhhhhh, ignored that. Now it's working, thanks!

**Comment by ellenmellon** [comment]
Actually, you may want to set `—passages_per_question_predict ` back to 20, as you don’t want to use a much smaller number of candidate passages for inference, which would hurt the performance greatly :)

**Comment by ellenmellon** [comment]
If you run into any memory issue during validation / inference stage, you can set a smaller `—dev_batch_size`.
